title: Linley Bignoux
description: My Jekyll site hosted on GitHub Pages
url: "https://linleybignoux.github.io"
baseurl: ""

author:
  name: Linley Bignoux
  email: linley@example.com
  github: linleybignoux

theme: minima

markdown: kramdown
